# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 14:52
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_topicprio", "0002_remove_category_related_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="description",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="topic",
            name="item_ptr",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="meinberlin_topicprio_topic",
                serialize=False,
                to="a4modules.Item",
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="name",
            field=models.CharField(max_length=120, verbose_name="Name"),
        ),
    ]
