# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 13:24
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import TextField


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_topicprio", "0005_alter_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="description",
            field=TextField(),
        ),
    ]
