# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-05 13:07
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("a4labels", "0001_initial"),
        ("meinberlin_topicprio", "0007_topic_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="labels",
            field=models.ManyToManyField(
                related_name="meinberlin_topicprio_topic_label", to="a4labels.Label"
            ),
        ),
    ]
