# Generated by Django 2.2.20 on 2021-05-07 14:56

from django.db import migrations
from django.db.models import TextField


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_topicprio", "0010_new_topic_image_verbose_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="description",
            field=TextField(verbose_name="Description"),
        ),
    ]
