# Generated by Django 2.2.20 on 2021-05-07 14:56

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_topicprio", "0010_new_topic_image_verbose_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                verbose_name="Description"
            ),
        ),
    ]
