# Generated by Django 3.2.16 on 2023-01-12 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_moderatorfeedback", "0004_alter_moderatorstatement_statement"),
    ]

    operations = [
        migrations.RenameField(
            model_name="moderatorstatement",
            old_name="statement",
            new_name="feedback_text",
        ),
    ]
