# Generated by Django 3.2.20 on 2023-10-12 14:46

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    dependencies = [
        ("meinberlin_moderatorfeedback", "0007_verbose_name_created_modified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moderatorfeedback",
            name="feedback_text",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True,
                help_text="The feedback appears below the idea or proposal, indicating your organisation. The creator of the contribution receives a notification.",
                verbose_name="Feedback (public)",
            ),
        ),
    ]
