# Generated by Django 4.2 on 2023-11-27 10:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meinberlin_votes", "0006_token_packages"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="tokenvote",
            new_name="meinberlin__content_b6aca7_idx",
            old_fields=("content_type", "object_pk"),
        ),
    ]
