# Generated by Django 4.2.22 on 2025-08-25 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("a4actions", "0010_alter_action_verb"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("meinberlin_kiezradar", "0007_alter_projectstatus_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_newsletter", models.BooleanField(default=False)),
                ("notify_followers_phase_started", models.BooleanField(default=True)),
                ("notify_followers_phase_over_soon", models.BooleanField(default=True)),
                ("notify_followers_event_upcoming", models.BooleanField(default=True)),
                ("notify_creator", models.BooleanField(default=True)),
                (
                    "notify_creator_on_moderator_feedback",
                    models.BooleanField(default=True),
                ),
                (
                    "notify_initiators_project_created",
                    models.BooleanField(default=True),
                ),
                ("notify_moderator", models.BooleanField(default=True)),
                ("track_followers_phase_started", models.BooleanField(default=True)),
                ("track_followers_phase_over_soon", models.BooleanField(default=True)),
                ("track_followers_event_upcoming", models.BooleanField(default=True)),
                ("track_creator", models.BooleanField(default=True)),
                (
                    "track_creator_on_moderator_feedback",
                    models.BooleanField(default=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="a4actions.action",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "search_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="meinberlin_kiezradar.searchprofile",
                    ),
                ),
            ],
        ),
    ]
