# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 14:56
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a4projects', '0008_project_tile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='information',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='This description should tell participants what the goal of the project is, how the project’s participation will look like. It will be always visible in the „Info“ tab on your project’s page.', verbose_name='Description of your project'),
        ),
    ]
