# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-16 12:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a4projects', '0016_add_verbose_for_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Phone numbers can only contain digits, spaces and the following characters: -, +, (, ). It has to be between 8 and 20 characters long.', regex='^[\\d\\+\\(\\)\\- ]{8,20}$')]),
        ),
    ]
