# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-25 10:14
from __future__ import unicode_literals

import adhocracy4.projects.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a4projects', '0018_add_location_and_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='topic',
            new_name='topics',
        ),
    ]
