# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-25 09:24
from __future__ import unicode_literals

import adhocracy4.projects.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a4projects', '0018_add_location_and_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='topic',
        ),
        migrations.AddField(
            model_name='project',
            name='topics',
            field=adhocracy4.projects.fields.TopicField(blank=True, choices=[('ANT', 'Anti-discrimination'), ('WOR', 'Work & economy'), ('BUI', 'Building & living'), ('EDU', 'Education & research'), ('CHI', 'Children, youth & family'), ('FIN', 'Finances'), ('HEA', 'Health & sports'), ('INT', 'Integration'), ('CUL', 'Culture & leisure'), ('NEI', 'Neighborhood & participation'), ('URB', 'Urban development'), ('ENV', 'Environment & public green space'), ('TRA', 'Traffic')], default='', max_length=254, verbose_name='Project topics'),
        ),
    ]
