# Generated by Django 2.2.3 on 2019-10-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a4projects', '0024_group_on_delete_set_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Archived projects are not shown in the project overview. For project initiators they are still visible in the dashboard.', verbose_name='Project is archived'),
        ),
    ]
