# Generated by Django 2.2.16 on 2020-10-22 10:15

import django_enumfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a4projects", "0027_use_collapsiblefield_results"),
    ]

    operations = []
