# Generated by Django 2.2.16 on 2020-10-22 10:15

import django_enumfield.db.fields
from django.db import migrations

import adhocracy4.projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('a4projects', '0027_use_collapsiblefield_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='access',
            field=django_enumfield.db.fields.EnumField(default=1, enum=adhocracy4.projects.enums.Access, help_text='Please indicate whether this project should be public or restricted to invited users. Teasers for your project including title and short description will always be visible to everyone'),
        ),
    ]
