# Generated by Django 2.2.16 on 2020-10-21 13:46

from django.db import migrations

from adhocracy4.projects.models import Access


def initialize_access(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Project = apps.get_model('a4projects', 'Project')
    for project in Project.objects.all():
        if project.is_public:
            project.access = Access.PUBLIC
        else:
            project.access = Access.PRIVATE
        project.save()


class Migration(migrations.Migration):

    dependencies = [
        ('a4projects', '0028_project_access'),
    ]

    operations = [
        migrations.RunPython(initialize_access),
    ]
