# Generated by Django 2.2.16 on 2020-12-03 10:39

import django_enumfield.db.fields
from django.db import migrations

import adhocracy4.projects.enums


class Migration(migrations.Migration):

    dependencies = [
        ('a4projects', '0030_remove_project_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='access',
            field=django_enumfield.db.fields.EnumField(
                default=1, enum=adhocracy4.projects.enums.Access),
        ),
    ]
