# Generated by Django 2.2.19 on 2021-03-29 11:55

import adhocracy4.images.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a4projects', '0031_remove_access_helptext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=adhocracy4.images.fields.ConfiguredImageField('heroimage', blank=True, help_prefix='The image will be shown as a decorative background image.', max_length=300, upload_to='projects/backgrounds', verbose_name='Header image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tile_image',
            field=adhocracy4.images.fields.ConfiguredImageField('tileimage', blank=True, help_prefix='The image will be shown in the project tile.', max_length=300, upload_to='projects/tiles', verbose_name='Tile image'),
        ),
    ]
