# Generated by Django 2.2.18 on 2021-05-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a4projects', '0032_increase_image_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_app_accessible',
            field=models.BooleanField(default=False),
        ),
    ]
