# Generated by Django 2.2.24 on 2021-08-24 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a4projects", "0033_project_is_app_accessible"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="project",
            name="contact_phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone numbers can only contain digits, "
                        "spaces and the following characters: -, +, (, ). "
                        "It has to be between 8 and 20 characters long.",
                        regex="^[\\d\\+\\(\\)\\- ]{8,20}$",
                    )
                ],
                verbose_name="Phone",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="contact_url",
            field=models.URLField(blank=True, verbose_name="Website"),
        ),
    ]
