# Generated by Django 3.2.12 on 2022-02-22 09:31

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a4projects", "0034_contact_mixin_help_texts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=True, populate_from="name", unique=True
            ),
        ),
    ]
