# Generated by Django 3.2.13 on 2022-06-20 07:44

import adhocracy4.images.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a4projects", "0036_alter_project_tile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="tile_image",
            field=adhocracy4.images.fields.ConfiguredImageField(
                "tileimage",
                blank=True,
                help_prefix="The image will be shown in the project tile.",
                max_length=300,
                upload_to="projects/tiles",
                verbose_name="Tile image",
            ),
        ),
    ]
