# Generated by Django 3.2.16 on 2024-09-10 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a4modules", "0007_auto_20240910_1142"),
        ("a4follows", "0002_delete_follow"),
        ("a4projects", "0037_alter_project_tile_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Project",
        ),
    ]
