# Generated by Django 3.2.19 on 2023-06-14 12:31

import adhocracy4.images.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("a4projects", "0038_verbose_name_created_modified"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="image_alt_text",
            field=adhocracy4.images.fields.ImageAltTextField(
                blank=True,
                help_text="An alternate text serves as a textual description of the image content and is read out by screen readers. Describe the image in max. 80 characters. Example: A busy square with people in summer.",
                max_length=80,
                verbose_name="Header image alt text",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="tile_image_alt_text",
            field=adhocracy4.images.fields.ImageAltTextField(
                blank=True,
                help_text="An alternate text serves as a textual description of the image content and is read out by screen readers. Describe the image in max. 80 characters. Example: A busy square with people in summer.",
                max_length=80,
                verbose_name="Tile image alt text",
            ),
        ),
    ]
