# Generated by Django 4.0 on 2023-11-07 15:26

import adhocracy4.projects.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("a4projects", "0041_ckeditor5_iframes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="topics",
            field=adhocracy4.projects.fields.TopicField(
                choices=[
                    ("ANT", "Anti-discrimination"),
                    ("WOR", "Work & economy"),
                    ("BUI", "Building & living"),
                ],
                default="",
                help_text="Add topics to your project.",
                max_length=254,
                verbose_name="Project topics",
            ),
        ),
    ]
