# Generated by Django 4.2 on 2023-11-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("a4projects", "0042_alter_project_topics"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=10)),
                ("name", models.CharField(max_length=120, verbose_name="Topic")),
            ],
        ),
        migrations.RemoveField(
            model_name="project",
            name="topics",
        ),
        migrations.AddField(
            model_name="project",
            name="topics",
            field=models.ManyToManyField(to="a4projects.topic"),
        ),
    ]
