# Generated by Django 4.2 on 2023-11-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("a4projects", "0043_migrate_topics_to_m2m_topics"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="topics",
        ),
    ]
