# Generated by Django 4.2.13 on 2024-08-27 11:34

import adhocracy4.images.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a4projects", "0046_alter_project_information_alter_project_result"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=adhocracy4.images.fields.ConfiguredImageField(
                "heroimage",
                blank=True,
                help_prefix="The image will be shown as a decorative background image.",
                max_length=300,
                upload_to="projects/backgrounds/%Y/%m/%d/",
                verbose_name="Header image",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="tile_image",
            field=adhocracy4.images.fields.ConfiguredImageField(
                "tileimage",
                blank=True,
                help_prefix="The image will be shown in the project tile.",
                max_length=300,
                upload_to="projects/tiles/%Y/%m/%d/",
                verbose_name="Tile image",
            ),
        ),
    ]
