# Generated by Django 4.2.17 on 2025-01-28 14:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a4projects", "0047_alter_project_image_alter_project_tile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="geos_point",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                help_text="Locate your project. Click inside the marked area or type in an address to set the marker. A set marker can be dragged when pressed.",
                null=True,
                srid=4326,
                verbose_name="Can your project be located on the map?",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="house_number",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="street_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="zip_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
