# Generated by Django 4.2.17 on 2025-02-19 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a4projects", "0049_migrate_data_from_point_to_geos_point"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="point",
        ),
    ]
