# Generated by Django 4.2.17 on 2025-02-19 15:49

from django.db import migrations


def migrate_project_geos_point_field(apps, schema_editor):
    project = apps.get_model("a4projects", "Project")
    for project in project.objects.all():
        if project.geos_point:
            project.point = project.geos_point
            project.save()


class Migration(migrations.Migration):

    dependencies = [
        ("a4projects", "0051_project_add_point_field"),
    ]

    operations = [
        migrations.RunPython(
            migrate_project_geos_point_field, reverse_code=migrations.RunPython.noop
        ),
    ]
