# Generated by Django 5.1.11 on 2025-08-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a4projects", "0052_project_remove_geos_point_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "running"), (1, "future"), (2, "done")],
                        verbose_name="Status",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "participation",
                    models.SmallIntegerField(
                        choices=[
                            (0, "information (no participation)"),
                            (1, "consultation"),
                            (2, "cooperation"),
                            (3, "decision-making"),
                        ],
                        verbose_name="Type",
                    ),
                ),
            ],
        ),
    ]
