# Generated by Django 5.1.13 on 2025-12-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a4projects", "0052_project_remove_geos_point_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.CharField(
                help_text="This short description will appear on the header of the project and in the teaser. It should briefly state the goal of the project in max. 170 chars.",
                max_length=250,
                verbose_name="Short description of your project",
            ),
        ),
    ]
