# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 09:14
from __future__ import unicode_literals

from django.db import migrations

from meinberlin.apps.adminlog.models import LogEntry


def clear_log(apps, schema_editor):
    LogEntry.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_adminlog", "0001_initial"),
    ]

    operations = [migrations.RunPython(clear_log)]
