# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 09:21
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("a4projects", "0011_fix_copyright_field_desc"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectContainer",
            fields=[
                (
                    "project_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="a4projects.Project",
                    ),
                ),
                (
                    "projects",
                    models.ManyToManyField(
                        related_name="containers", to="a4projects.Project"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("a4projects.project",),
        ),
    ]
