# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 11:39
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_projectcontainers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectcontainer",
            name="projects",
            field=models.ManyToManyField(
                related_name="containers",
                to="a4projects.Project",
                verbose_name="Projects",
            ),
        ),
    ]
