# Generated by Django 2.2.6 on 2019-11-04 12:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meinberlin_projectcontainers", "0002_verbose_name"),
        ("meinberlin_projects", "0002_custom_project_types"),
    ]

    operations = [migrations.RunPython(migrations.RunPython.noop)]
