# Generated by Django 3.2.20 on 2023-12-04 12:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("a4follows", "0002_verbose_name_created_modified"),
        ("meinberlin_offlineevents", "0008_alter_offlineevent_description"),
        ("a4modules", "0007_verbose_name_created_modified"),
        ("a4actions", "0008_set_action_obj_comment_creator"),
        ("a4comments", "0013_set_project"),
        ("meinberlin_newsletters", "0008_alter_newsletter_body"),
        ("meinberlin_projects", "0004_verbose_name_created_modified"),
        ("meinberlin_plans", "0057_alter_plan_description"),
        ("meinberlin_projectcontainers", "0004_delete_projectcontainer"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProjectContainer",
        ),
    ]
