# Generated by Django 2.2.13 on 2020-07-07 12:04

from django.db import migrations
from django.db.models import TextField


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_newsletters", "0005_update_descriptions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="body",
            field=TextField(
                blank=True,
                help_text="When adding images, please ensure to set the width no larger than 650px.",
                verbose_name="Email body",
            ),
        ),
    ]
