# Generated by Django 4.2.9 on 2024-01-30 13:56

from adhocracy4.images.validators import ImageAltTextValidator
from django.db import migrations
from django_ckeditor_5.fields import CKEditor5Field


class Migration(migrations.Migration):
    dependencies = [
        ("meinberlin_newsletters", "0009_alter_newsletter_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="body",
            field=CKEditor5Field(
                blank=True,
                validators=[ImageAltTextValidator()],
                verbose_name="Email body",
            ),
        ),
    ]
