# Generated by Django 3.2.16 on 2022-11-22 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a4labels", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="label",
            options={"ordering": ["pk"], "verbose_name_plural": "labels"},
        ),
    ]
