# Generated by Django 3.2.16 on 2024-09-10 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a4labels", "0002_alter_label_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Label",
        ),
    ]
