# Generated by Django 4.2.17 on 2025-05-26 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("a4projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name="Modified"
                    ),
                ),
                ("object_pk", models.PositiveIntegerField()),
                ("comment", models.TextField(max_length=4000)),
                ("is_removed", models.BooleanField(default=False)),
                ("is_censored", models.BooleanField(default=False)),
                ("is_blocked", models.BooleanField(default=False)),
                ("comment_categories", models.CharField(blank=True, max_length=256)),
                (
                    "last_discussed",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("is_moderator_marked", models.BooleanField(default=False)),
                ("is_reviewed", models.BooleanField(default=False)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="a4projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
                "ordering": ("created",),
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_pk"],
                        name="a4comments__content_ff606b_idx",
                    )
                ],
            },
        ),
    ]
