# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-04 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("a4comments", "0004_comment_char_limit_increase"),
    ]

    """
        IndexTogether has been removed in django 5.1 
        and migrations had to be updated to reflect that. 
        Django versions prior to 4, that have already 
        deployed the migrations would not be affected
    """
    # TODO: delete commented out operations code once the upgrade 5.1 has been deployed and tested
    #    operations = [
    #        migrations.AlterIndexTogether(
    #            name="comment",
    #            index_together=set([("content_type", "object_pk")]),
    #        ),
    #    ]

    operations = [
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=("content_type", "object_pk"),
                name="a4comments__content_ff606b_idx",
            ),
        ),
    ]
