# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-04 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('a4comments', '0004_comment_char_limit_increase'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='comment',
            index_together=set([('content_type', 'object_pk')]),
        ),
    ]
