# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-04 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("a4comments", "0004_comment_char_limit_increase"),
    ]

    #    Dont worked with Django 5 so i had to change that manually so that the migration structure stays
    #    Works now for news installations with Django 4 and 5 and for existing installations with older Django where this migration was already applied
    #    operations = [
    #        migrations.AlterIndexTogether(
    #            name="comment",
    #            index_together=set([("content_type", "object_pk")]),
    #        ),
    #    ]

    operations = [
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=("content_type", "object_pk"),
                name="a4comments__content_ff606b_idx",
            ),
        ),
    ]
