# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-18 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a4comments', '0005_auto_20181204_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='last_discussed',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
