# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-09 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a4comments', '0006_comment_last_discussed'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_moderator_marked',
            field=models.BooleanField(default=False),
        ),
    ]
