# Generated by Django 2.2.10 on 2020-02-13 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a4comments', '0007_comment_is_moderator_marked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_moderator_marked',
        ),
    ]
