# Generated by Django 3.2.7 on 2021-11-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a4comments", "0008_comment_is_deleted_empty_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_blocked",
            field=models.BooleanField(default=False),
        ),
    ]
