# Generated by Django 3.2.16 on 2022-11-14 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('a4modules', '0006_module_blueprint_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a4modules.module')),
            ],
            options={
                'verbose_name_plural': 'moderation tasks',
            },
        ),
    ]
