# Generated by Django 3.2.16 on 2022-11-23 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_moderationtasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="moderationtask",
            options={"ordering": ["pk"], "verbose_name_plural": "moderation tasks"},
        ),
    ]
