# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-04 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("a4actions", "0003_set_default_ordering_to_timestamp"),
    ]

    #    operations = [
    #        migrations.AlterIndexTogether(
    #            name="action",
    #            index_together=set([("obj_content_type", "obj_object_id")]),
    #        ),
    #    ]

    operations = [
        migrations.AddIndex(
            model_name="action",
            index=models.Index(
                fields=("obj_content_type", "obj_object_id"),
                name="a4actions_a_obj_con_ee317e_idx",
            ),
        ),
    ]
