# Generated by Django 3.2.19 on 2023-06-05 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("a4actions", "0006_set_action_target_creator"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="obj_comment_creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="obj_comment_creator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
