# Generated by Django 4.2 on 2023-11-27 12:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("a4actions", "0008_set_action_obj_comment_creator"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="action",
            new_name="a4actions_a_obj_con_ee317e_idx",
            old_fields=("obj_content_type", "obj_object_id"),
        ),
    ]
