# Generated by Django 4.2.17 on 2025-02-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "a4actions",
            "0009_rename_action_obj_content_type_obj_object_id_a4actions_a_obj_con_ee317e_idx",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="verb",
            field=models.CharField(
                choices=[
                    ("create", "CREATE"),
                    ("add", "ADD"),
                    ("update", "UPDATE"),
                    ("complete", "COMPLETE"),
                    ("schedule", "SCHEDULE"),
                    ("start", "START"),
                    ("publish", "PUBLISH"),
                ],
                db_index=True,
                max_length=255,
            ),
        ),
    ]
