# Generated by Django 5.2.1 on 2025-05-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a4actions", "0010_alter_action_verb"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="action",
            name="a4actions_a_obj_con_ee317e_idx",
        ),
        migrations.AddIndex(
            model_name="action",
            index=models.Index(
                fields=("obj_content_type", "obj_object_id"),
                name="a4actions_a_obj_con_ee317e_idx",
            ),
        ),
    ]
