# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-20 14:54
from __future__ import unicode_literals

import adhocracy4.files.fields
import autoslug.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('a4projects', '0014_collapsible_information_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(blank=True, editable=False, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('name', models.CharField(max_length=120, verbose_name='Title')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Description')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a4projects.Project')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='OfflineEventDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=256)),
                ('document', adhocracy4.files.fields.ConfiguredFileField('offlineevents', help_prefix='The document may be downloaded from the event page.', upload_to='offlineevents/documents', verbose_name='Document')),
                ('offlineevent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='a4offlineevents.OfflineEvent')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
