# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 13:42
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_extprojects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalproject",
            name="url",
            field=models.URLField(blank=True),
        ),
    ]
