# Generated by Django 2.2.19 on 2021-03-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_extprojects", "0005_custom_project_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalproject",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="Please enter a full url which starts with https:// or http://",
                max_length=500,
                verbose_name="URL",
            ),
        ),
    ]
