# Generated by Django 2.2.16 on 2020-11-16 15:40

from django.db import migrations
from django.db.models import TextField


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_livequestions", "0002_livestream"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livestream",
            name="live_stream",
            field=TextField(
                blank=True,
                help_text="You can enter a livestream from YouTube or Vimeo. The livestream will be shown when the module phase is active. For description text please use module or phase description.",
                verbose_name="Livestream",
            ),
        ),
    ]
