# Generated by Django 3.2.20 on 2023-10-12 14:46

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    dependencies = [
        ("meinberlin_livequestions", "0004_verbose_name_created_modified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livestream",
            name="live_stream",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True,
                help_text="You can enter a livestream from YouTube or Vimeo. The livestream will be shown when the module phase is active. For description text please use module or phase description.",
                verbose_name="Livestream",
            ),
        ),
    ]
