# Generated by Django 3.2.20 on 2023-11-16 11:35

from bs4 import BeautifulSoup
from django.db import migrations


def replace_iframe_with_figur(apps, schema_editor):
    template = (
        '<figure class="media"><div data-oembed-url="{url}"><div><iframe src="'
        '{url}"></iframe></div></div></figure>'
    )
    liveevents = 0
    LiveStream = apps.get_model("meinberlin_livequestions", "LiveStream")
    for livestream in LiveStream.objects.all():
        soup = BeautifulSoup(livestream.live_stream, "html.parser")
        iframes = soup.findAll("iframe")
        for iframe in iframes:
            figure = BeautifulSoup(
                template.format(url=iframe.attrs["src"]), "html.parser"
            )
            iframe.replaceWith(figure)
            liveevents += 1
        if iframes:
            livestream.live_stream = soup.prettify(formatter="html")
            livestream.save()


class Migration(migrations.Migration):
    dependencies = [
        ("meinberlin_livequestions", "0005_alter_livestream_live_stream"),
    ]

    operations = [
        migrations.RunPython(
            replace_iframe_with_figur,
        ),
    ]
