# Generated by Django 3.2.16 on 2024-09-10 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a4polls", "0004_change_wording_helptext"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="choice",
            name="question",
        ),
        migrations.RemoveField(
            model_name="othervote",
            name="vote",
        ),
        migrations.RemoveField(
            model_name="poll",
            name="item_ptr",
        ),
        migrations.RemoveField(
            model_name="question",
            name="poll",
        ),
        migrations.RemoveField(
            model_name="vote",
            name="choice",
        ),
        migrations.RemoveField(
            model_name="vote",
            name="creator",
        ),
        migrations.DeleteModel(
            name="Answer",
        ),
        migrations.DeleteModel(
            name="Choice",
        ),
        migrations.DeleteModel(
            name="OtherVote",
        ),
        migrations.DeleteModel(
            name="Poll",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
        migrations.DeleteModel(
            name="Vote",
        ),
    ]
