# Generated by Django 5.1.11 on 2025-10-20 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a4polls", "0006_alter_answer_unique_together_answer_content_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="poll",
            options={"base_manager_name": "objects"},
        ),
    ]
