# Generated by Django 5.2.10 on 2026-01-12 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a4polls", "0007_alter_poll_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="poll",
            options={},
        ),
    ]
