# Generated by Django 5.2.8 on 2026-06-10 07:12

import adhocracy4.images.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a4polls", "0008_question_is_confidential"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="image",
            field=adhocracy4.images.fields.ConfiguredImageField(
                "heroimage",
                blank=True,
                help_prefix="The image will be shown with the question",
                max_length=300,
                upload_to="projects/polls/",
                verbose_name="Image for Question",
            ),
        ),
    ]
