# Generated by Django 5.2.8 on 2026-06-16 12:00

import adhocracy4.images.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a4polls", "0009_question_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="image_alt_text",
            field=adhocracy4.images.fields.ImageAltTextField(
                blank=True,
                image_name="Question image",
                max_length=80,
            ),
        ),
    ]
