# Generated by Django 5.2.14 on 2026-07-14 12:44

import adhocracy4.images.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a4polls", "0010_question_image_alt_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="image",
            field=adhocracy4.images.fields.ConfiguredImageField(
                "questionimage",
                blank=True,
                help_prefix="The image will be shown with the question",
                max_length=300,
                upload_to="projects/polls/",
                verbose_name="Image for Question",
            ),
        ),
    ]
