# Generated by Django 4.2.17 on 2025-05-26 13:12

import adhocracy4.maps.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("a4modules", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AreaSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "polygon",
                    adhocracy4.maps.fields.MultiPolygonField(
                        help_text="Please draw an area on the map.",
                        verbose_name="Polygon",
                    ),
                ),
                (
                    "module",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_settings",
                        to="a4modules.module",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
