# Generated by Django 4.2 on 2023-11-29 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("a4modules", "0008_alter_module_blueprint_type"),
        ("a4maps", "0002_change_help_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="areasettings",
            name="module",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_settings",
                to="a4modules.module",
            ),
        ),
    ]
