# Generated by Django 4.2.17 on 2025-05-26 13:12

import adhocracy4.categories.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0001_initial"),
        ("a4categories", "0001_initial"),
        ("a4modules", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenVote",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name="Modified"
                    ),
                ),
                ("object_pk", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "item_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="a4modules.item",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        default="Can i haz cheezburger, pls?", max_length=120
                    ),
                ),
                (
                    "last_discussed",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "category",
                    adhocracy4.categories.fields.CategoryField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="a4categories.category",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("a4modules.item",),
        ),
    ]
