# Generated by Django 5.1.11 on 2025-10-20 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a4test_questions", "0007_verbose_name_created_modified"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"base_manager_name": "objects"},
        ),
    ]
