# Generated by Django 5.1.13 on 2026-01-12 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a4test_questions", "0008_alter_question_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={},
        ),
    ]
