# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 13:07
from __future__ import unicode_literals

import adhocracy4.maps.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meinberlin_mapideas', '0007_add_default_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapidea',
            name='point',
            field=adhocracy4.maps.fields.PointField(help_text='Click inside marked area on the map to set a marker. Drag and drop the marker to change its place. Alternatively you can use the search field to search for an address.', verbose_name='Where can your idea be located on a map?'),
        ),
    ]
