# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meinberlin_ideas', '0006_auto_20170529_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Title'),
        ),
    ]
