# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-07 16:26
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations
from django.db import models

import meinberlin.apps.moderatorfeedback.fields


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_moderatorfeedback", "0001_initial"),
        ("meinberlin_ideas", "0009_remove_universal_phase"),
    ]

    operations = [
        migrations.AddField(
            model_name="idea",
            name="moderator_feedback",
            field=meinberlin.apps.moderatorfeedback.fields.ModeratorFeedbackField(
                blank=True,
                choices=[
                    ("CONSIDERATION", "Under consideration"),
                    ("REJECTED", "Rejected"),
                    ("ACCEPTED", "Accepted"),
                ],
                default=None,
                max_length=254,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="idea",
            name="moderator_statement",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="meinberlin_moderatorfeedback.ModeratorStatement",
            ),
        ),
    ]
