# Generated by Django 2.2.5 on 2019-09-05 09:16

from django.db import migrations
import meinberlin.apps.moderatorfeedback.fields


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_ideas", "0015_add_verbose_for_idea_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idea",
            name="moderator_feedback",
            field=meinberlin.apps.moderatorfeedback.fields.ModeratorFeedbackField(
                blank=True,
                choices=[
                    ("CONSIDERATION", "Under consideration"),
                    ("REJECTED", "Rejected"),
                    ("ACCEPTED", "Accepted"),
                ],
                default=None,
                help_text="The editing status appears below the title of the idea in red, yellow or green. The idea provider receives a notification.",
                max_length=254,
                null=True,
                verbose_name="Processing status",
            ),
        ),
    ]
