# Generated by Django 3.2.20 on 2023-09-18 14:46

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('meinberlin_ideas', '0021_rename_moderatorfeedback_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description'),
        ),
    ]
