# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 08:04
from __future__ import unicode_literals

from django.db import migrations
from django.db import models

import adhocracy4.maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_kiezkasse", "0007_allow_blank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposal",
            name="name",
            field=models.CharField(max_length=120, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="point",
            field=adhocracy4.maps.fields.PointField(
                help_text="Click inside marked area on the map to set a marker. Drag and drop the marker to change its place. Alternatively you can use the search field to search for an address.",
                verbose_name="Where can your idea be located on a map?",
            ),
        ),
    ]
