# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-08 12:19
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_organisations", "0005_organisation_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="type",
            field=models.CharField(
                choices=[
                    ("DA", "district administration"),
                    ("CA", "city administration"),
                    ("NM", "neighbourhood management"),
                    ("OT", "other"),
                ],
                default="OT",
                max_length=2,
            ),
        ),
    ]
