# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-04 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_organisations", "0006_update_orga_type_string"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organisation",
            name="type",
        ),
    ]
