# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-06 14:48
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_organisations", "0007_remove_organisation_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="address",
            field=models.TextField(blank=True, verbose_name="Unit and postal address"),
        ),
        migrations.AddField(
            model_name="organisation",
            name="url",
            field=models.URLField(blank=True, verbose_name="Website of organisation"),
        ),
    ]
