# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-11 16:03
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0008_alter_user_username_max_length"),
        ("meinberlin_organisations", "0008_add_url_and_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="groups",
            field=models.ManyToManyField(blank=True, to="auth.Group"),
        ),
    ]
