# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-28 09:24
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_organisations", "0009_organisation_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="address",
            field=models.TextField(blank=True, verbose_name="Postal address"),
        ),
    ]
