# Generated by Django 3.2.11 on 2022-02-22 13:36

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_organisations", "0011_update_logo_helptext"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=True, populate_from="name", unique=True
            ),
        ),
    ]
