# Generated by Django 3.2.16 on 2023-01-13 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moderatorfeedback", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="moderatorstatement",
            old_name="statement",
            new_name="feedback_text",
        ),
    ]
