# Generated by Django 3.2.20 on 2023-09-19 13:10

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    dependencies = [
        ("moderatorfeedback", "0004_verbose_name_created_modified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moderatorfeedback",
            name="feedback_text",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
    ]
