# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-16 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meinberlin_moderatorremark', '0002_unique_by_foreignobject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderatorremark',
            name='remark',
            field=models.TextField(blank=True, verbose_name='Remark'),
        ),
    ]
