# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 13:43
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_bplan", "0004_add_verbose_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bplan",
            name="office_worker_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Office worker email"
            ),
        ),
    ]
