# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-19 14:57
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_bplan", "0005_make_office_worker_email_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="bplan",
            name="identifier",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Identifier"
            ),
        ),
    ]
