# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-08 13:46
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_bplan", "0006_bplan_identifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bplan",
            name="identifier",
            field=models.CharField(
                blank=True,
                help_text="The identifier has to be identic to the identifier in the FIS-Broker, so that district and location are added automatically.",
                max_length=120,
                verbose_name="Identifier",
            ),
        ),
    ]
