# Generated by Django 2.2.6 on 2019-11-04 12:39

from django.db import migrations


def add_project_type(apps, schema_editor):
    Bplan = apps.get_model("meinberlin_bplan", "Bplan")
    objs = Bplan.objects.all()
    for obj in objs:
        obj.project_type = "meinberlin_bplan.Bplan"
    Bplan.objects.bulk_update(objs, ["project_type"])


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_bplan", "0007_add_helptext_to_identifier"),
        ("meinberlin_extprojects", "0005_custom_project_types"),
    ]

    operations = [migrations.RunPython(add_project_type)]
