# Generated by Django 2.2.13 on 2020-07-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_bplan", "0008_custom_project_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statement",
            name="statement",
            field=models.TextField(verbose_name="Statement"),
        ),
    ]
