# Generated by Django 4.2.17 on 2025-05-26 13:12

import adhocracy4.categories.fields
import adhocracy4.maps.fields
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("a4categories", "0001_initial"),
        ("moderatorfeedback", "0001_initial"),
        ("a4modules", "0001_initial"),
        ("a4labels", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Idea",
            fields=[
                (
                    "item_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="a4modules.item",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Can i haz cheezburger, pls?", max_length=120
                    ),
                ),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="Description"
                    ),
                ),
                ("moderator_status", models.CharField(blank=True, max_length=256)),
                ("point", adhocracy4.maps.fields.PointField(blank=True)),
                (
                    "point_label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="This could be an address or the name of a landmark.",
                        max_length=255,
                        verbose_name="Label of the ideas location",
                    ),
                ),
                ("is_bool_test", models.BooleanField(default=True)),
                (
                    "category",
                    adhocracy4.categories.fields.CategoryField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="a4categories.category",
                        verbose_name="Category",
                    ),
                ),
                (
                    "labels",
                    models.ManyToManyField(
                        related_name="%(app_label)s_%(class)s_label",
                        to="a4labels.label",
                    ),
                ),
                (
                    "moderator_feedback_text",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="moderatorfeedback.moderatorfeedback",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("a4modules.item",),
        ),
    ]
