# Generated by Django 3.2.7 on 2021-09-28 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('a4test_moderatorfeedback', '0001_initial'),
        ('a4test_ideas', '0002_idea_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='moderator_feedback',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='idea',
            name='moderator_statement',
            field=models.OneToOneField(blank=True, null=True,
                                       on_delete=django.db.models.deletion.CASCADE,
                                       related_name='+',
                                       to='a4test_moderatorfeedback.moderatorstatement'),
        ),
    ]
