# Generated by Django 3.2.16 on 2023-01-13 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a4test_ideas", "0003_idea_moderator_feedback_moderator_statement"),
    ]

    operations = [
        migrations.RenameField(
            model_name="idea",
            old_name="moderator_statement",
            new_name="moderator_feedback_text",
        ),
        migrations.RenameField(
            model_name="idea",
            old_name="moderator_feedback",
            new_name="moderator_status",
        ),
    ]
