# Generated by Django 3.2.17 on 2023-02-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("a4test_ideas", "0004_rename_moderator_feedback_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="idea",
            name="is_bool_test",
            field=models.BooleanField(default=True),
        ),
    ]
