# Generated by Django 3.2.20 on 2023-09-19 13:10

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    dependencies = [
        ("a4test_ideas", "0005_idea_is_bool_test"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idea",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, verbose_name="Description"
            ),
        ),
    ]
