# Generated by Django 5.1.11 on 2025-10-20 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a4test_ideas", "0007_alter_idea_labels"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="idea",
            options={"base_manager_name": "objects"},
        ),
    ]
