# Generated by Django 5.2.13 on 2026-06-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a4test_ideas", "0008_alter_idea_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="idea",
            name="creator_contact_consent",
            field=models.BooleanField(
                default=False, verbose_name="Creator contact consent"
            ),
        ),
        migrations.AddField(
            model_name="idea",
            name="creator_email",
            field=models.EmailField(
                blank=True,
                default="",
                max_length=254,
                verbose_name="Creator email address",
            ),
        ),
        migrations.AddField(
            model_name="idea",
            name="creator_phone",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                verbose_name="Creator phone number",
            ),
        ),
    ]
