# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-09 12:19
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_users", "0004_update_help_texts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="get_newsletters",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether you want to receive newsletters. Unselect if you do not want to receive newsletters.",
                verbose_name="Send me newsletters",
            ),
        ),
    ]
