# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-11 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meinberlin_users', '0005_default_user_newsletter_is_false'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='groups', to='auth.Group'),
        ),
    ]
