# Generated by Django 3.2.16 on 2024-09-10 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a4organisations", "0002_organisation_slug"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Organisation",
        ),
    ]
