# Generated by Django 5.1.13 on 2025-11-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a4administrative_districts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="administrativedistrict",
            name="short_code",
            field=models.CharField(
                blank=True,
                help_text='2-character code for the district (e.g., "mi" for Mitte)',
                max_length=2,
                verbose_name="Short code",
            ),
        ),
    ]
