# Generated by Django 3.2.16 on 2024-09-10 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a4administrative_districts", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AdministrativeDistrict",
        ),
    ]
