# Generated by Django 3.2.16 on 2024-09-10 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a4test_organisations", "0003_organisationtermsofuse"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organisation",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="organisation",
            name="initiators",
        ),
        migrations.AlterUniqueTogether(
            name="organisationtermsofuse",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="organisationtermsofuse",
            name="organisation",
        ),
        migrations.RemoveField(
            model_name="organisationtermsofuse",
            name="user",
        ),
        migrations.DeleteModel(
            name="Member",
        ),
        migrations.DeleteModel(
            name="Organisation",
        ),
        migrations.DeleteModel(
            name="OrganisationTermsOfUse",
        ),
    ]
