# Generated by Django 2.2.2 on 2019-06-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_offlineevents", "0004_event_type_form_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offlineevent",
            name="event_type",
            field=models.CharField(
                help_text="The content of this field is shown in the timeline. It should have no more than 30 characters e.g. Information event or 3rd public workshop.",
                max_length=30,
                verbose_name="Event type",
            ),
        ),
    ]
