# Generated by Django 2.2.16 on 2020-09-16 15:15

import adhocracy4.ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_offlineevents", "0005_remove_default_for_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offlineevent",
            name="description",
            field=adhocracy4.ckeditor.fields.RichTextCollapsibleUploadingField(
                verbose_name="Description"
            ),
        ),
    ]
