# Generated by Django 2.2.16 on 2020-09-16 15:15

from django.db import migrations
from django.db.models import TextField


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_offlineevents", "0005_remove_default_for_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offlineevent",
            name="description",
            field=TextField(verbose_name="Description"),
        ),
    ]
