# Generated by Django 4.2.9 on 2024-01-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meinberlin_offlineevents", "0008_alter_offlineevent_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offlineevent",
            name="event_type",
            field=models.CharField(max_length=30, verbose_name="Event type"),
        ),
    ]
