# Generated by Django 4.2.9 on 2024-01-30 13:56

import adhocracy4.images.validators
from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    dependencies = [
        ("meinberlin_offlineevents", "0009_alter_offlineevent_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offlineevent",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                validators=[adhocracy4.images.validators.ImageAltTextValidator()],
                verbose_name="Description",
            ),
        ),
    ]
