# Generated by Django 2.2.14 on 2020-07-13 11:36

from django.db import migrations
from django.db.models import TextField


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_platformemails", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platformemail",
            name="body",
            field=TextField(
                blank=True,
                help_text="When adding images, please ensure to set the width no larger than 650px.",
                verbose_name="Email body",
            ),
        ),
    ]
