# Generated by Django 4.2.9 on 2024-01-23 16:33

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    dependencies = [
        ("meinberlin_platformemails", "0004_alter_platformemail_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platformemail",
            name="body",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, verbose_name="Email body"
            ),
        ),
    ]
