# Generated by Django 3.2.16 on 2024-09-10 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a4ratings", "0003_auto_20181204_1309"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Rating",
        ),
    ]
