# Generated by Django 4.2 on 2023-11-27 12:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("a4ratings", "0004_verbose_name_created_modified"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="rating",
            new_name="a4ratings_r_content_8fb00e_idx",
            old_fields=("content_type", "object_pk"),
        ),
    ]
