# Generated by Django 2.2.6 on 2019-10-30 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a4phases', '0006_remove_weight_from_phase_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phase',
            options={'ordering': ['weight', 'id']},
        ),
    ]
