# Generated by Django 3.2.16 on 2024-09-10 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a4phases", "0007_order_phases_also_by_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Phase",
        ),
    ]
