# Generated by Django 3.2.16 on 2024-09-10 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a4follows", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Follow",
        ),
    ]
