# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 11:40
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_plans", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="budget",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Budget"
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="category",
            field=models.CharField(
                default="", max_length=255, verbose_name="Type of plan"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plan",
            name="contact",
            field=models.TextField(default="", max_length=255, verbose_name="Contact"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plan",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="plan",
            name="participation",
            field=models.SmallIntegerField(
                choices=[(1, "Yes"), (0, "No"), (2, "Still undecided")], default=2
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plan",
            name="point_label",
            field=models.CharField(
                blank=True,
                default="",
                help_text="This could be an address or the name of a landmark.",
                max_length=255,
                verbose_name="Label of the location",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="status",
            field=models.SmallIntegerField(
                choices=[
                    (0, "Idea"),
                    (1, "Planning"),
                    (2, "Implementation"),
                    (3, "Done"),
                    (4, "Stopped"),
                ],
                default=0,
            ),
            preserve_default=False,
        ),
    ]
