# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 13:35
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_plans", "0002_extend_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="budget",
        ),
        migrations.AddField(
            model_name="plan",
            name="cost",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Cost"
            ),
        ),
    ]
