# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-20 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meinberlin_plans', '0003_rename_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='slug',
        ),
    ]
