# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-20 15:27
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_plans", "0007_make_plan_description_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="district",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="meinberlin_maps.MapPreset",
                verbose_name="District",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="participation",
            field=models.SmallIntegerField(
                choices=[(1, "Yes"), (0, "No"), (2, "Still undecided")],
                verbose_name="Participation",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="a4projects.Project",
                verbose_name="Project",
            ),
        ),
    ]
