# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-16 15:11
from __future__ import unicode_literals

from django.db import migrations


def make_many_projects(apps, schema_editor):
    Plan = apps.get_model("meinberlin_plans", "Plan")

    for plan in Plan.objects.all():
        if plan.project:
            plan.projects.add(plan.project)


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_plans", "0009_plan_projects"),
    ]

    operations = [migrations.RunPython(make_many_projects)]
