# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-16 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_plans", "0010_copy_projects"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="project",
        ),
    ]
