# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 08:57
from __future__ import unicode_literals

from django.db import migrations

import adhocracy4.images.fields


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_plans", "0011_remove_plan_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="description_image",
            field=adhocracy4.images.fields.ConfiguredImageField(
                "description_image",
                blank=True,
                upload_to="plan/description_image",
                verbose_name="Add image",
            ),
        ),
    ]
