# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 09:58
from __future__ import unicode_literals

from django.db import migrations

import adhocracy4.images.fields


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_plans", "0012_plan_description_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="description_image",
            field=adhocracy4.images.fields.ConfiguredImageField(
                "plan_image",
                blank=True,
                help_prefix="Visualize your plan.",
                upload_to="plan/description_image",
                verbose_name="Add image",
            ),
        ),
    ]
