# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-19 14:56
from __future__ import unicode_literals

from django.db import migrations


def copy_costs(apps, schema_editor):
    Plan = apps.get_model("meinberlin_plans", "Plan")
    for plan in Plan.objects.all():
        plan.cost_string = str(plan.cost)
        plan.save()


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_plans", "0014_plan_cost_string"),
    ]

    operations = [
        migrations.RunPython(copy_costs),
    ]
