# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-20 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_plans", "0015_copy_costs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="cost",
        ),
    ]
