# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-20 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_plans", "0016_remove_plan_cost"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plan",
            old_name="cost_string",
            new_name="cost",
        ),
    ]
