# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-20 15:06
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_plans", "0018_point_label_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="point_label",
            field=models.CharField(
                default="Label of the location",
                help_text="The label of the location is displayed in the detail view of the plan",
                max_length=255,
                verbose_name="Label of the location",
            ),
        ),
    ]
