# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-20 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meinberlin_plans', '0020_contact_2000_chars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meinberlin_maps.MapPreset', verbose_name='District'),
        ),
    ]
