# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_plans", "0023_point_label_default_value"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plan",
            old_name="category",
            new_name="theme",
        ),
    ]
