# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 12:05
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_plans", "0024_rename_category_to_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="theme",
            field=models.CharField(max_length=255, verbose_name="Theme"),
        ),
    ]
