# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-13 13:09
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("a4administrative_districts", "0001_initial"),
        ("meinberlin_plans", "0025_verbose_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="administrative_district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="a4administrative_districts.AdministrativeDistrict",
                verbose_name="District",
            ),
        ),
    ]
