# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-13 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_plans", "0026_plan_administrative_district"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="district",
        ),
    ]
