# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-13 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_plans", "0027_remove_plan_district"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plan",
            old_name="administrative_district",
            new_name="district",
        ),
    ]
