# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-11 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_plans", "0029_add_topics"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plan",
            old_name="theme",
            new_name="topic",
        ),
    ]
