# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-28 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meinberlin_plans', '0030_rename_theme_to_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='participation',
            field=models.SmallIntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Still undecided')], verbose_name='Participation'),
        ),
    ]
