# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-25 14:28
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_plans", "0030_rename_theme_to_topic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="status",
            field=models.SmallIntegerField(choices=[(0, "Ongoing"), (1, "Done")]),
        ),
    ]
