# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-28 13:27
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_plans", "0032_rename_topic_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="participation",
            field=models.SmallIntegerField(
                choices=[(0, "Yes"), (1, "No"), (2, "Still undecided")],
                verbose_name="Participation",
            ),
        ),
    ]
