# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-04 09:56
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_plans", "0033_change_order_participation_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="participation",
            field=models.SmallIntegerField(
                choices=[(0, "with"), (1, "without"), (2, "undecided")],
                verbose_name="Participation",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="status",
            field=models.SmallIntegerField(choices=[(0, "ongoing"), (1, "done")]),
        ),
    ]
