# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-06 15:38
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models

import adhocracy4.projects.fields


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_plans", "0034_choice_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.A4_ORGANISATIONS_MODEL,
                verbose_name="Organisation",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="status",
            field=models.SmallIntegerField(
                choices=[(0, "ongoing"), (1, "done")], verbose_name="Status"
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="topics",
            field=adhocracy4.projects.fields.TopicField(
                choices=[
                    ("ANT", "Anti-discrimination"),
                    ("WOR", "Work & economy"),
                    ("BUI", "Building & living"),
                    ("EDU", "Education & research"),
                    ("CHI", "Children, youth & family"),
                    ("FIN", "Finances"),
                    ("HEA", "Health & sports"),
                    ("INT", "Integration"),
                    ("CUL", "Culture & leisure"),
                    ("NEI", "Neighborhood & participation"),
                    ("URB", "Urban development"),
                    ("ENV", "Environment & public green space"),
                    ("TRA", "Traffic"),
                ],
                default="",
                max_length=254,
                verbose_name="Topics",
            ),
        ),
    ]
