# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-20 13:59
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_plans", "0037_helptext_topics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="status",
            field=models.SmallIntegerField(
                choices=[(0, "running"), (1, "done")], verbose_name="Status"
            ),
        ),
    ]
