# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-03 11:40
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_plans", "0039_plan_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="auth.Group",
            ),
        ),
    ]
