# Generated by Django 2.2.24 on 2021-08-11 07:37

import adhocracy4.maps.fields
import adhocracy4.projects.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_plans", "0043_make_cost_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="contact",
            field=models.TextField(
                help_text="Please name a contact person so users know who to contact with any questions they may have.",
                max_length=1000,
                verbose_name="Contact for queries",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="cost",
            field=models.CharField(
                help_text="Enter details of the estimated or actual costs of the plan in no more than 255 characters.",
                max_length=255,
                verbose_name="Cost",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="description",
            field=models.TextField(
                help_text="Describe the cornerstones of your plan. You can upload PDFs and images, embed videos and link to external URLs.",
                verbose_name="Description of your plan",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="district",
            field=models.ForeignKey(
                blank=True,
                help_text="Enter the district in which the plan is located or whether it is a city-wide plan. In the project overview projects can be filtered by district.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="a4administrative_districts.AdministrativeDistrict",
                verbose_name="District",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="duration",
            field=models.CharField(
                blank=True,
                help_text="Provide information on the expected duration of the plan in no more than 255 characters.",
                max_length=255,
                null=True,
                verbose_name="Duration",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="participation",
            field=models.SmallIntegerField(
                choices=[(0, "with"), (1, "without"), (2, "undecided")],
                help_text="In the project overview projects can be filtered according to participation status.",
                verbose_name="Participation",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="point",
            field=adhocracy4.maps.fields.PointField(
                blank=True,
                help_text="If you locate your plan, it will be shown on the map in the project overview in addition to the list. To set a pin, click inside the highlighted area or enter an address. Once a pin is set you can move it by dragging it.",
                verbose_name="Can your plan be located on the map?",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="point_label",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The name of the site (e.g. name of street, building or park) makes it easier to locate the plan. The maximum length is 255 characters.",
                max_length=255,
                verbose_name="Name of the site",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="status",
            field=models.SmallIntegerField(
                choices=[(0, "running"), (1, "done")],
                help_text="In the project overview projects can be filtered by status.",
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="title",
            field=models.CharField(
                help_text="Enter a meaningful title with a maximum length of 120 characters. The title will appear in the project tile and on top of the plan detail page.",
                max_length=120,
                verbose_name="Title of your plan",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="topics",
            field=adhocracy4.projects.fields.TopicField(
                choices=[
                    ("ANT", "Anti-discrimination"),
                    ("WOR", "Work & economy"),
                    ("BUI", "Building & living"),
                    ("EDU", "Education & research"),
                    ("CHI", "Children, youth & family"),
                    ("FIN", "Finances"),
                    ("HEA", "Health & sports"),
                    ("INT", "Integration"),
                    ("CUL", "Culture & leisure"),
                    ("NEI", "Neighborhood & participation"),
                    ("URB", "Urban development"),
                    ("ENV", "Environment & public green space"),
                    ("TRA", "Traffic"),
                ],
                default="",
                help_text="Assign your plan to 1 or 2 topics. In the project overview projects can be filtered according to topics.",
                max_length=254,
                verbose_name="Topics",
            ),
        ),
    ]
