# Generated by Django 2.2.24 on 2021-08-16 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meinberlin_plans', '0044_plan_adapt_help_texts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='contact',
            new_name='contact_address_text',
        ),
    ]
