# Generated by Django 2.2.24 on 2021-08-23 09:42

import adhocracy4.images.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meinberlin_plans', '0047_use_a4_richtextfield_for_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='tile_image',
            field=adhocracy4.images.fields.ConfiguredImageField('tileimage', blank=True, help_prefix='The image will be shown in the project tile.', upload_to='plan/tile_images', verbose_name='Tile image'),
        ),
        migrations.AddField(
            model_name='plan',
            name='tile_image_copyright',
            field=adhocracy4.images.fields.ImageCopyrightField(blank=True, help_text='Copyright shown in the Tile image.', max_length=120, verbose_name='Tile image copyright'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='description_image',
            field=adhocracy4.images.fields.ConfiguredImageField('plan_image', blank=True, help_prefix='Visualize your plan with an image underneath the description.', upload_to='plan/description_image', verbose_name='Header image'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='description_image_copyright',
            field=models.CharField(blank=True, max_length=120, verbose_name='Header image copyright'),
        ),
    ]
