# Generated by Django 3.2.11 on 2022-02-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_plans", "0052_alter_plan_participation"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="participation_explanation",
            field=models.TextField(
                default="Bitte Begründung einfügen",
                help_text="Justify your selection. The justification appears below the description of the project.",
                max_length=4000,
                verbose_name="Participation explanation",
            ),
        ),
    ]
