# Generated by Django 3.2.12 on 2022-03-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meinberlin_plans', '0053_plan_participation_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='participation_explanation',
            field=models.TextField(help_text='Justify your selection. The justification appears below the description of the project.', max_length=4000, verbose_name='Participation explanation'),
        ),
    ]
