# Generated by Django 4.2 on 2023-11-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("a4projects", "0045_rename_field_m2mtopics_to_topics"),
        ("meinberlin_plans", "0057_alter_plan_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="m2mtopics",
            field=models.ManyToManyField(
                help_text="Assign your plan to 1 or 2 topics. In the project overview projects can be filtered according to topics.",
                to="a4projects.topic",
                verbose_name="Topics",
            ),
        ),
    ]
