# Generated by Django 4.2 on 2023-11-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("a4projects", "0045_rename_field_m2mtopics_to_topics"),
        ("meinberlin_plans", "0059_migrate_topics_to_m2m_topics"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="topics",
        ),
    ]
