# Generated by Django 4.2 on 2023-11-30 14:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "meinberlin_plans",
            "0060_remove_plan_m2mtopics_remove_plan_topics_plan_topics",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="plan",
            old_name="m2mtopics",
            new_name="topics",
        ),
    ]
