# Generated by Django 4.2.9 on 2024-01-23 16:33

import adhocracy4.images.fields
import adhocracy4.maps.fields
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    dependencies = [
        ("a4administrative_districts", "0001_initial"),
        ("a4projects", "0045_rename_field_m2mtopics_to_topics"),
        ("meinberlin_plans", "0061_rename_m2mtopics_plan_topics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="cost",
            field=models.CharField(max_length=255, verbose_name="Cost"),
        ),
        migrations.AlterField(
            model_name="plan",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                verbose_name="Description of your plan"
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="a4administrative_districts.administrativedistrict",
                verbose_name="District",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="duration",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Duration"
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="image_copyright",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Header image copyright"
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="participation",
            field=models.SmallIntegerField(
                choices=[
                    (0, "information (no participation)"),
                    (1, "consultation"),
                    (2, "cooperation"),
                    (3, "decision-making"),
                ],
                default=0,
                verbose_name="Level of participation",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="participation_explanation",
            field=models.TextField(
                max_length=4000, verbose_name="Participation explanation"
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="point",
            field=adhocracy4.maps.fields.PointField(
                blank=True, verbose_name="Can your plan be located on the map?"
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="point_label",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Name of the site"
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="status",
            field=models.SmallIntegerField(
                choices=[(0, "running"), (1, "done")], verbose_name="Status"
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="tile_image_copyright",
            field=adhocracy4.images.fields.ImageCopyrightField(
                blank=True,
                help_text="Copyright shown in the image.",
                max_length=120,
                verbose_name="Tile image copyright",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="title",
            field=models.CharField(max_length=120, verbose_name="Title of your plan"),
        ),
        migrations.AlterField(
            model_name="plan",
            name="topics",
            field=models.ManyToManyField(to="a4projects.topic", verbose_name="Topics"),
        ),
    ]
