# Generated by Django 3.2.20 on 2023-11-16 11:35

from bs4 import BeautifulSoup
from django.db import migrations


def replace_iframe_with_figur(apps, schema_editor):
    template = (
        '<figure class="media"><div data-oembed-url="{url}"><div><iframe src="'
        '{url}"></iframe></div></div></figure>'
    )
    Plan = apps.get_model("meinberlin_plans", "Plan")
    for plan in Plan.objects.all():
        soup = BeautifulSoup(plan.description, "html.parser")
        iframes = soup.findAll("iframe")
        for iframe in iframes:
            figure = BeautifulSoup(
                template.format(url=iframe.attrs["src"]), "html.parser"
            )
            iframe.replaceWith(figure)
        if iframes:
            plan.description = soup.prettify(formatter="html")
            plan.save()


class Migration(migrations.Migration):
    dependencies = [
        ("meinberlin_plans", "0063_alter_plan_description"),
    ]

    operations = [
        migrations.RunPython(
            replace_iframe_with_figur,
        ),
    ]
