# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-05 13:26
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("a4labels", "0001_initial"),
        ("meinberlin_maptopicprio", "0005_maptopic_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="maptopic",
            name="labels",
            field=models.ManyToManyField(
                related_name="meinberlin_maptopicprio_maptopic_label",
                to="a4labels.Label",
            ),
        ),
    ]
