# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-04 08:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_maptopicprio", "0007_add_label_verbose_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="maptopic",
            options={"ordering": ["-created"], "verbose_name": "maptopic"},
        ),
    ]
