# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-28 16:49
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_maptopicprio", "0009_point_helptext"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maptopic",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                verbose_name="Description"
            ),
        ),
    ]
