# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-28 16:49
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import TextField


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_maptopicprio", "0009_point_helptext"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maptopic",
            name="description",
            field=TextField(verbose_name="Description"),
        ),
    ]
