# Generated by Django 3.2.20 on 2023-09-19 09:44

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    dependencies = [
        ("meinberlin_maptopicprio", "0010_change_verbose_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maptopic",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Description"),
        ),
    ]
