# Generated by Django 4.2.9 on 2024-01-23 16:33

import adhocracy4.maps.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "meinberlin_maptopicprio",
            "0012_alter_maptopic_item_ptr_alter_maptopic_labels",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="maptopic",
            name="point",
            field=adhocracy4.maps.fields.PointField(
                verbose_name="Where can your idea be located on a map?"
            ),
        ),
        migrations.AlterField(
            model_name="maptopic",
            name="point_label",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Label of the ideas location",
            ),
        ),
    ]
