# Generated by Django 4.2.9 on 2024-01-30 13:56

from adhocracy4.images.validators import ImageAltTextValidator
from django.db import migrations
from django_ckeditor_5.fields import CKEditor5Field


class Migration(migrations.Migration):
    dependencies = [
        (
            "meinberlin_maptopicprio",
            "0013_alter_maptopic_point_alter_maptopic_point_label",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="maptopic",
            name="description",
            field=CKEditor5Field(
                validators=[ImageAltTextValidator()],
                verbose_name="Description",
            ),
        ),
    ]
