# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-15 14:44
from __future__ import unicode_literals

import adhocracy4.categories.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a4categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=adhocracy4.categories.models.IconField(blank=True, default='', max_length=254),
        ),
    ]
