# Generated by Django 3.2.16 on 2024-09-10 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a4reports", "0002_auto_20181204_1650"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Report",
        ),
    ]
