# Generated by Django 4.2 on 2023-11-27 12:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("a4reports", "0003_verbose_name_created_modified"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="report",
            new_name="a4reports_r_content_75c7cc_idx",
            old_fields=("content_type", "object_pk"),
        ),
    ]
