# Generated by Django 3.2.20 on 2023-09-19 09:44

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    dependencies = [
        ("meinberlin_documents", "0008_verbose_name_created_modified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paragraph",
            name="text",
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
