# Generated by Django 4.2.9 on 2024-01-30 13:56

from adhocracy4.images.validators import ImageAltTextValidator
from django.db import migrations
from django_ckeditor_5.fields import CKEditor5Field


class Migration(migrations.Migration):
    dependencies = [
        ("meinberlin_documents", "0009_alter_paragraph_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paragraph",
            name="text",
            field=CKEditor5Field(validators=[ImageAltTextValidator()]),
        ),
    ]
