# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-13 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a4modules', '0003_rm_unique_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.CharField(blank=True, help_text='This short description will appear on the header of the module and project detail pages. It should briefly state the goal of the module in max. 512 chars.', max_length=512, null=True, verbose_name='Short description of the module'),
        ),
    ]
