# Generated by Django 3.2.13 on 2022-06-28 14:30

import adhocracy4.modules.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a4modules", "0005_module_is_draft"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="blueprint_type",
            field=adhocracy4.modules.fields.BlueprintTypeField(
                blank=True, max_length=255
            ),
        ),
    ]
