# Generated by Django 3.2.16 on 2024-09-10 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a4labels", "0003_delete_label"),
        ("a4categories", "0004_delete_category"),
        ("a4maps", "0003_delete_areasettings"),
        ("a4phases", "0008_delete_phase"),
        ("a4modules", "0006_module_blueprint_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="module",
            name="project",
        ),
        migrations.DeleteModel(
            name="Item",
        ),
        migrations.DeleteModel(
            name="Module",
        ),
    ]
