# Generated by Django 4.0 on 2023-11-07 15:26

import adhocracy4.modules.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("a4modules", "0007_verbose_name_created_modified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="module",
            name="blueprint_type",
            field=adhocracy4.modules.fields.BlueprintTypeField(
                blank=True, choices=[], max_length=255
            ),
        ),
    ]
