# Generated by Django 4.2 on 2023-11-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("a4modules", "0007_verbose_name_created_modified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="module",
            name="blueprint_type",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
