# Generated by Django 4.2 on 2023-11-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("a4modules", "0008_alter_module_blueprint_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="module",
            name="blueprint_type",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
