# Generated by Django 5.2.10 on 2026-01-12 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a4modules", "0010_populate_item_polymorphic_ctype"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={},
        ),
    ]
