# Generated by Django 3.2.15 on 2022-09-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_budgeting", "0023_disallow_contact_for_existing_proposals"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposal",
            name="budget",
            field=models.PositiveIntegerField(
                default=0,
                help_text='Please enter the estimated or actual costs for your proposal. Enter 0€ if the costs are not (yet) known. In this case, the description "budget not specified" will appear in your proposal.',
                verbose_name="Budget",
            ),
        ),
    ]
