# Generated by Django 3.2.16 on 2022-11-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_budgeting", "0029_alter_proposal_moderator_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposal",
            name="is_archived",
            field=models.BooleanField(
                default=False,
                help_text="Exclude this proposal from all listings by default. You can still access this proposal by using filters.",
                verbose_name="Proposal is archived (public)",
            ),
        ),
    ]
