# Generated by Django 4.2.13 on 2024-10-24 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("a4modules", "0009_optionaluseritem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("is_other_choice", models.BooleanField(default=False)),
                ("weight", models.SmallIntegerField()),
            ],
            options={
                "ordering": ["weight", "id"],
            },
        ),
        migrations.CreateModel(
            name="OpenPoll",
            fields=[
                (
                    "optionaluseritem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="a4modules.optionaluseritem",
                    ),
                ),
                ("allow_unregistered_users", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
            bases=("a4modules.optionaluseritem",),
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name="Modified"
                    ),
                ),
                ("content_id", models.UUIDField(blank=True, null=True)),
                (
                    "choice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="a4open_poll.choice",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "default_related_name": "openpoll_vote",
            },
        ),
        migrations.CreateModel(
            name="OtherVote",
            fields=[
                (
                    "vote",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="other_vote",
                        serialize=False,
                        to="a4open_poll.vote",
                    ),
                ),
                ("answer", models.CharField(max_length=250, verbose_name="Answer")),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                (
                    "help_text",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Explanation"
                    ),
                ),
                ("weight", models.SmallIntegerField()),
                ("multiple_choice", models.BooleanField(default=False)),
                ("is_open", models.BooleanField(default=False)),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="a4open_poll.openpoll",
                    ),
                ),
            ],
            options={
                "ordering": ["weight"],
            },
        ),
        migrations.AddField(
            model_name="choice",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choices",
                to="a4open_poll.question",
            ),
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name="Modified"
                    ),
                ),
                ("content_id", models.UUIDField(blank=True, null=True)),
                ("answer", models.CharField(max_length=750, verbose_name="Answer")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="a4open_poll.question",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "default_related_name": "openpoll_answer",
                "unique_together": {("question", "creator", "content_id")},
            },
        ),
    ]
