# Generated by Django 2.2.24 on 2021-06-18 11:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a4modules', '0005_module_is_draft'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meinberlin_polls', '0004_question_multiple_choice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='MBChoice',
        ),
        migrations.RenameModel(
            old_name='Poll',
            new_name='MBPoll',
        ),
        migrations.RenameModel(
            old_name='Question',
            new_name='MBQuestion',
        ),
        migrations.RenameModel(
            old_name='Vote',
            new_name='MBVote',
        ),
    ]
