# Generated by Django 2.2.24 on 2021-09-01 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meinberlin_polls', '0006_copy_poll_data_to_a4_polls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mbquestion',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='mbvote',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='mbvote',
            name='creator',
        ),
        migrations.DeleteModel(
            name='MBChoice',
        ),
        migrations.DeleteModel(
            name='MBQuestion',
        ),
        migrations.DeleteModel(
            name='MBVote',
        ),
    ]
