# Generated by Django 2.2.24 on 2021-09-01 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meinberlin_polls', '0007_remove_choice_question_vote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MBPoll',
        ),
    ]
