# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-27 12:41
from __future__ import unicode_literals

import adhocracy4.ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meinberlin_activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=adhocracy4.ckeditor.fields.RichTextCollapsibleUploadingField(verbose_name='Description'),
        ),
    ]
