# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-27 12:41
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import TextField


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_activities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="description",
            field=TextField(verbose_name="Description"),
        ),
    ]
