# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-07 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meinberlin_activities', '0002_use_collapsible_ck_for_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='highlight',
            field=models.CharField(help_text='Highlight important information like the time or location of your face-to-face event', max_length=120, verbose_name='Highlighted Info'),
        ),
    ]
