# Generated by Django 3.2.20 on 2023-10-12 14:46

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    dependencies = [
        ("meinberlin_activities", "0003_add_helptext"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Description"),
        ),
    ]
