# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meinberlin_cms', '0015_adapt_to_wagtail_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailformpage',
            name='attach_as',
            field=models.CharField(blank=True, choices=[('xls', 'XLSX Document'), ('txt', 'Text File')], help_text='Form results are send in this document format', max_length=3, null=True),
        ),
    ]
