# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 16:14
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_cms", "0015_adapt_to_wagtail_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailformpage",
            name="attach_as",
            field=models.CharField(
                choices=[
                    ("inc", "Include in Email"),
                    ("xls", "XLSX Document"),
                    ("txt", "Text File"),
                ],
                default="inc",
                help_text="Form results are send in this document format",
                max_length=3,
            ),
        ),
    ]
