# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-18 09:48
from __future__ import unicode_literals

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0040_page_draft_title"),
        ("meinberlin_cms", "0018_add_imgage_cta_block"),
    ]

    operations = [
        migrations.CreateModel(
            name="StreamfieldSimplePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        (
                            ("paragraph", wagtail.blocks.RichTextBlock()),
                            ("html", wagtail.blocks.RawHTMLBlock()),
                        ),
                        blank=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
