# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-24 12:30
from __future__ import unicode_literals

import wagtail.core.blocks
import wagtail.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meinberlin_cms', '0019_add_streamfieldsimplepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docspage',
            name='body',
            field=wagtail.core.fields.StreamField((('documents_list', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock()), ('body', wagtail.core.blocks.RichTextBlock(required=False))))), ('header', wagtail.core.blocks.CharBlock(template='meinberlin_cms/blocks/header.html')))),
        ),
    ]
