# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-29 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meinberlin_cms", "0021_add_storefront"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="storefrontcollection",
            options={},
        ),
        migrations.RemoveField(
            model_name="storefrontcollection",
            name="sort_order",
        ),
    ]
