# Generated by Django 3.2.17 on 2023-02-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meinberlin_cms", "0040_storefront_add_numbers_as_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="storefrontitem",
            name="district_project_count",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
